/** Shared toast contract: transient confirmations that float above layout. */
import type { ReactNode } from 'react';

export type ToastTone = 'success' | 'warn' | 'error';

export type ToastExitReason =
  | 'timeout'
  | 'swipe'
  | 'action'
  | 'close'
  | 'escape'
  | 'programmatic';

export type ToastFuse = 'top' | 'bottom' | 'none';

export interface ToastItem {
  /** Stable id (generated by the queue when omitted on push). */
  id: string;
  /** First line. PINs and error details never belong here. */
  message: ReactNode;
  /** Dimmer second line. Empty hides it. */
  description?: ReactNode;
  /** 18px slot before the text. Defaults to the tone icon. */
  icon?: ReactNode;
  /** Inverted action button. Empty hides it. */
  actionLabel?: ReactNode;
  /** Called when the action is pressed, before closing. */
  onAction?: () => void;
  /** Which edge the burn line runs along. */
  fuse?: ToastFuse;
  tone?: ToastTone;
  /**
   * Milliseconds until auto-dismiss. Re-arms when changed.
   * 0 = sticky until dismissed.
   */
  duration?: number;
}

export interface ToastPush extends Omit<ToastItem, 'id'> {
  id?: string;
}

export interface ToastItemProps {
  toast: ToastItem;
  /** Slow-drag distance before release dismisses. A flick always does. */
  swipeDistance?: number;
  /** Snap-back overshoot after an abandoned swipe. 0 stops dead. */
  settleBounce?: number;
  /** Rise and drop duration. */
  slideMs?: number;
  /** Hovering freezes the fuse line and its timer. */
  pauseOnHover?: boolean;
  /** Adds a cross at the end of the row. */
  closeButton?: boolean;
  /** Off removes the swipe and Escape. */
  dismissible?: boolean;
  onExit: (id: string, reason: ToastExitReason) => void;
}
