/** Shared toast contract: transient confirmations that float above layout. */

export type ToastTone = 'success' | 'warn' | 'error';

export type ToastExitReason =
  | 'timeout'
  | 'swipe'
  | 'close'
  | 'escape'
  | 'programmatic';

export interface ToastItem {
  /** Stable id (generated by the queue when omitted on push). */
  id: string;
  /** Short confirmation text (no PINs, no error details). */
  message: string;
  tone?: ToastTone;
  /**
   * Milliseconds until auto-dismiss. Re-arms when changed.
   * 0 = sticky until dismissed.
   */
  duration?: number;
}

export interface ToastPush extends Omit<ToastItem, 'id'> {
  id?: string;
}
