"""Rebuild every icon from the one drawing of Q'uq' (public/icons/quq.svg).

Run from pwa/tareas/segundo after editing quq.svg:   python tools/render-icons.py
Needs Google Chrome (headless, to turn SVG into PNG) and Pillow.

Writes public/icons/icon.svg, icon-192.png, icon-512.png and the Android launcher foreground
../android/app/src/main/res/drawable-nodpi/ic_launcher_foreground.png.
"""

import re
import subprocess
import tempfile
from pathlib import Path

from PIL import Image

APP = Path(__file__).resolve().parent.parent
ICONS = APP / "public" / "icons"
ANDROID_FG = APP.parent / "android/app/src/main/res/drawable-nodpi/ic_launcher_foreground.png"
CHROME = next(
    p
    for p in (
        Path(r"C:\Program Files\Google\Chrome\Application\chrome.exe"),
        Path("/usr/bin/google-chrome"),
        Path("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"),
    )
    if p.exists()
)

quq = (ICONS / "quq.svg").read_text(encoding="utf-8")
inner = re.search(r"<svg[^>]*>(.*)</svg>", quq, re.S).group(1)
view_box = re.search(r'viewBox="([^"]+)"', quq).group(1)


def quq_at(x, y, w, h):
    return f'<svg x="{x}" y="{y}" width="{w}" height="{h}" viewBox="{view_box}">{inner}</svg>'


# App icon: full-bleed sky so it also works as a maskable icon; Q'uq' stays inside the safe circle.
ICON = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
<!-- Generated by tools/render-icons.py from quq.svg: edit quq.svg, then re-run the script. -->
<defs><linearGradient id="sky" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#A5E4FA"/><stop offset="1" stop-color="#5BBFE6"/></linearGradient></defs>
<rect width="512" height="512" fill="url(#sky)"/>
<circle cx="398" cy="112" r="46" fill="#FFE082" opacity="0.9"/>
<ellipse cx="256" cy="560" rx="360" ry="150" fill="#43A047"/>
{quq_at(129, 76, 254, 360)}
</svg>
"""

# Android adaptive-icon foreground: transparent, Q'uq' inside the 66 dp safe zone of 108 dp.
FOREGROUND = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 432 432" width="512" height="512">{quq_at(128, 91, 176, 250)}</svg>'


def render(svg_text, out_png, size):
    with tempfile.TemporaryDirectory() as tmp:
        src = Path(tmp) / "in.svg"
        src.write_text(svg_text, encoding="utf-8")
        shot = Path(tmp) / "shot.png"
        subprocess.run(
            [str(CHROME), "--headless=new", "--disable-gpu", "--hide-scrollbars",
             "--force-device-scale-factor=1", "--default-background-color=00000000",
             "--window-size=512,512", f"--screenshot={shot}", src.as_uri()],
            check=True, capture_output=True,
        )
        img = Image.open(shot).convert("RGBA").crop((0, 0, 512, 512))
        img.resize((size, size), Image.LANCZOS).save(out_png)


(ICONS / "icon.svg").write_text(ICON, encoding="utf-8")
render(ICON, ICONS / "icon-512.png", 512)
render(ICON, ICONS / "icon-192.png", 192)
ANDROID_FG.parent.mkdir(parents=True, exist_ok=True)
render(FOREGROUND, ANDROID_FG, 432)
print("icons written")
