"""Centralized configuration package for TutorBox."""

from core.config.captive_settings import build_captive_portal_config
from core.config.constants import (
    DEFAULT_AUTH_LOCKOUT_SECONDS,
    DEFAULT_AUTH_MAX_ATTEMPTS,
    DEFAULT_AUTH_MAX_TRACKED_KEYS,
    DEFAULT_BCRYPT_ROUNDS,
    DEFAULT_BUSY_TIMEOUT_MS,
    DEFAULT_CAPTIVE_PORTAL_ENABLED,
    DEFAULT_CAPTIVE_PORTAL_URL,
    DEFAULT_DB_PATH,
    DEFAULT_QUIZ_MAX_RETRIES,
    DEFAULT_SEED_TEACHER_PIN,
    DEFAULT_SEED_TEACHER_USERNAME,
    DEFAULT_SIGNUP_MAX_EVENTS,
    DEFAULT_SIGNUP_WINDOW_SECONDS,
    DEFAULT_SLM_BASE_URL,
    DEFAULT_SLM_MODEL_NAME,
    DEFAULT_SLM_TEMPERATURE,
    DEFAULT_SLM_TIMEOUT_SECONDS,
    DEFAULT_TTS_AMPLITUDE,
    DEFAULT_TTS_BINARY,
    DEFAULT_TTS_ENABLED,
    DEFAULT_TTS_MAX_CHARS,
    DEFAULT_TTS_PITCH,
    DEFAULT_TTS_TIMEOUT_SECONDS,
    DEFAULT_TTS_VOICE,
    DEFAULT_TTS_VOICE_QUC,
    DEFAULT_TTS_WORDS_PER_MINUTE,
    PROJECT_ROOT,
)
from core.config.env_loader import load_env_file
from core.config.models import (
    CaptivePortalConfig,
    DatabaseConfig,
    LLMConfig,
    QuizConfig,
    SecurityConfig,
    Settings,
    TTSConfig,
)
from core.config.parsers import (
    parse_bool,
    parse_db_path,
    parse_float,
    parse_int,
)
from core.config.settings import (
    clear_settings_cache,
    get_settings,
)
from core.config.tts_settings import build_tts_config

__all__ = [
    "DEFAULT_AUTH_LOCKOUT_SECONDS",
    "DEFAULT_AUTH_MAX_ATTEMPTS",
    "DEFAULT_AUTH_MAX_TRACKED_KEYS",
    "DEFAULT_BCRYPT_ROUNDS",
    "DEFAULT_BUSY_TIMEOUT_MS",
    "DEFAULT_CAPTIVE_PORTAL_ENABLED",
    "DEFAULT_CAPTIVE_PORTAL_URL",
    "DEFAULT_DB_PATH",
    "DEFAULT_QUIZ_MAX_RETRIES",
    "DEFAULT_SEED_TEACHER_PIN",
    "DEFAULT_SEED_TEACHER_USERNAME",
    "DEFAULT_SIGNUP_MAX_EVENTS",
    "DEFAULT_SIGNUP_WINDOW_SECONDS",
    "DEFAULT_SLM_BASE_URL",
    "DEFAULT_SLM_MODEL_NAME",
    "DEFAULT_SLM_TEMPERATURE",
    "DEFAULT_SLM_TIMEOUT_SECONDS",
    "DEFAULT_TTS_AMPLITUDE",
    "DEFAULT_TTS_BINARY",
    "DEFAULT_TTS_ENABLED",
    "DEFAULT_TTS_MAX_CHARS",
    "DEFAULT_TTS_PITCH",
    "DEFAULT_TTS_TIMEOUT_SECONDS",
    "DEFAULT_TTS_VOICE",
    "DEFAULT_TTS_VOICE_QUC",
    "DEFAULT_TTS_WORDS_PER_MINUTE",
    "PROJECT_ROOT",
    "CaptivePortalConfig",
    "DatabaseConfig",
    "LLMConfig",
    "QuizConfig",
    "SecurityConfig",
    "Settings",
    "TTSConfig",
    "build_captive_portal_config",
    "build_tts_config",
    "clear_settings_cache",
    "get_settings",
    "load_env_file",
    "parse_bool",
    "parse_db_path",
    "parse_float",
    "parse_int",
]
